//! docs/reference/cli.md is the help of every command, as `iris COMMAND --help`
//! prints it, rendered from the same clap definitions. After a change to the
//! help text, update the page with `IRIS_UPDATE_DOCS=1 cargo test --test cli_reference`.

use clap::{Command, CommandFactory};
use iris::cli::args::Cli;

const PAGE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/docs/reference/cli.md");
const UPDATE: &str = "IRIS_UPDATE_DOCS=1 cargo test --test cli_reference";

/// Every command in the tree, depth first, with its full name: `iris`, `iris image`,
/// `iris image generate`, ... Clap's own `help` subcommands are left out.
fn commands(command: &Command, name: String, out: &mut Vec<(String, Command)>) {
    out.push((name.clone(), command.clone()));
    for sub in command.get_subcommands().filter(|sub| sub.get_name() != "help") {
        commands(sub, format!("{name} {}", sub.get_name()), out);
    }
}

/// The GitHub anchor of a `## iris image generate` heading.
fn anchor(name: &str) -> String {
    name.replace(' ', "-")
}

fn render() -> String {
    let mut root = Cli::command().term_width(100);
    root.build();
    let mut all = Vec::new();
    commands(&root, "iris".to_string(), &mut all);

    let mut page = String::from(
        "# CLI reference\n\n\
         This page shows the help of every Iris command, as `iris COMMAND --help` prints it. It's\n\
         generated from the same definitions as the help itself, so it matches the binary built from\n\
         the same commit. For the JSON that each command prints with `--json`, see the\n\
         [JSON output reference](json-output.md).\n\n",
    );
    page.push_str(&format!("<!-- Generated by tests/cli_reference.rs. To update it, run: {UPDATE} -->\n\n"));
    page.push_str("| Command | Description |\n|---|---|\n");
    for (name, command) in &all {
        let about = command.get_about().map(|about| about.to_string()).unwrap_or_default();
        page.push_str(&format!("| [`{name}`](#{}) | {about} |\n", anchor(name)));
    }
    for (name, command) in &mut all {
        let help = command.render_long_help().to_string();
        page.push_str(&format!("\n## {name}\n\n```text\n{}\n```\n", help.trim_end()));
    }
    page
}

#[test]
fn the_cli_reference_is_the_help_of_every_command() {
    let expected = render();
    if std::env::var_os("IRIS_UPDATE_DOCS").is_some() {
        std::fs::write(PAGE, &expected).expect("write docs/reference/cli.md");
        return;
    }
    let actual = std::fs::read_to_string(PAGE).unwrap_or_default();
    if actual != expected {
        let line = actual
            .lines()
            .zip(expected.lines())
            .position(|(a, e)| a != e)
            .map_or_else(|| actual.lines().count().min(expected.lines().count()) + 1, |index| index + 1);
        panic!("docs/reference/cli.md differs from the help from line {line}; update it with `{UPDATE}`");
    }
}

/// The page shows what the binary prints: `iris image generate --help` and the
/// page's section for it are the same text.
#[test]
fn the_cli_reference_matches_the_binary() {
    let page = render();
    let section = page
        .split_once("\n## iris image generate\n\n```text\n")
        .and_then(|(_, rest)| rest.split_once("\n```\n"))
        .map(|(help, _)| help.to_string())
        .expect("a section for iris image generate");
    // A clean environment: no credential of the developer's reaches the process.
    let out = std::process::Command::new(env!("CARGO_BIN_EXE_iris"))
        .args(["image", "generate", "--help"])
        .env_clear()
        .env("COLUMNS", "100")
        .output()
        .expect("run iris");
    assert!(out.status.success());
    assert_eq!(String::from_utf8(out.stdout).unwrap().trim_end(), section);
}
